<?php
namespace App\Http\Controllers\Api\V1;
use App\Application\Booking\{CancelBookingAction,CreateBookingAction}; use App\Exceptions\ApiProblem; use App\Http\Controllers\Controller; use App\Http\Requests\Booking\CreateBookingRequest; use App\Models\Booking; use Illuminate\Http\{JsonResponse,Request}; use Illuminate\Support\Facades\DB;
final class BookingController extends Controller {
    private array $relations=['trip.route.origin','trip.route.destination','trip.bus.operator','payments','passengers'];
    public function store(CreateBookingRequest $request,CreateBookingAction $action): JsonResponse { $booking=$action->execute($request->user(),$request->string('seat_hold_id')->toString(),$request->input('passengers')); return response()->json(['data'=>$this->serialize($booking)],201); }
    public function index(Request $request): JsonResponse { $items=Booking::query()->with($this->relations)->where('user_id',$request->user()->id)->latest()->paginate(15); $items->through(fn(Booking $b)=>$this->serialize($b)); return response()->json($items); }
    public function show(Request $request,Booking $booking): JsonResponse { $this->own($request,$booking); return response()->json(['data'=>$this->serialize($booking->load($this->relations))]); }
    public function cancel(Request $request,Booking $booking,CancelBookingAction $action): JsonResponse { $this->own($request,$booking); return response()->json(['data'=>$this->serialize($action->execute($booking,(string)$request->input('reason','Customer cancellation'))->load($this->relations))]); }
    private function own(Request $request,Booking $booking): void { if($booking->user_id!==$request->user()->id) throw new ApiProblem('FORBIDDEN','This booking does not belong to you.',403); }
    private function serialize(Booking $b): array { $passengers=$b->relationLoaded('passengers')?$b->passengers->map(function($p) use($b){$seat=DB::table('booking_seats')->join('trip_seats','trip_seats.id','=','booking_seats.trip_seat_id')->where('booking_seats.booking_id',$b->id)->where('booking_seats.passenger_id',$p->id)->value('trip_seats.seat_number');return ['id'=>$p->id,'full_name'=>$p->full_name,'phone'=>$p->phone,'email'=>$p->email,'seat'=>$seat];}):[]; $tickets=DB::table('tickets')->join('trip_seats','trip_seats.id','=','tickets.trip_seat_id')->join('booking_passengers','booking_passengers.id','=','tickets.passenger_id')->where('tickets.booking_id',$b->id)->get(['tickets.id','tickets.ticket_number','tickets.status','tickets.qr_payload','trip_seats.seat_number','booking_passengers.full_name as passenger_name']); return ['id'=>$b->id,'public_id'=>$b->public_id,'booking_reference'=>$b->booking_reference,'status'=>$b->status,'subtotal'=>$b->subtotal,'service_fee'=>$b->service_fee,'discount_amount'=>$b->discount_amount,'total_amount'=>$b->total_amount,'currency'=>$b->currency,'expires_at'=>$b->expires_at?->toIso8601String(),'confirmed_at'=>$b->confirmed_at?->toIso8601String(),'cancelled_at'=>$b->cancelled_at?->toIso8601String(),'trip'=>$b->relationLoaded('trip')?['id'=>$b->trip->id,'departure_at'=>$b->trip->departure_at->toIso8601String(),'arrival_at'=>$b->trip->arrival_at->toIso8601String(),'route'=>['origin'=>['id'=>$b->trip->route->origin->id,'name'=>$b->trip->route->origin->name,'slug'=>$b->trip->route->origin->slug],'destination'=>['id'=>$b->trip->route->destination->id,'name'=>$b->trip->route->destination->name,'slug'=>$b->trip->route->destination->slug],'code'=>$b->trip->route->code,'duration_minutes'=>$b->trip->route->estimated_duration_minutes],'bus'=>['id'=>$b->trip->bus->id,'label'=>$b->trip->bus->label,'type'=>$b->trip->bus->bus_type,'registration_number'=>$b->trip->bus->registration_number,'operator'=>['id'=>$b->trip->bus->operator->id,'name'=>$b->trip->bus->operator->name]]]:null,'passengers'=>$passengers,'payments'=>$b->relationLoaded('payments')?$b->payments->map(fn($p)=>['id'=>$p->id,'public_id'=>$p->public_id,'booking_id'=>$p->booking_id,'provider'=>$p->provider,'provider_transaction_id'=>$p->provider_transaction_id,'amount'=>$p->amount,'currency'=>$p->currency,'status'=>$p->status,'paid_at'=>$p->paid_at?->toIso8601String()]):[],'tickets'=>$tickets]; }
}
