<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
    public function up(): void {
        Schema::create('bookings', function (Blueprint $table): void { $table->ulid('id')->primary(); $table->string('public_id',32)->unique(); $table->string('booking_reference',24)->unique(); $table->foreignUlid('user_id')->constrained()->restrictOnDelete(); $table->foreignUlid('trip_id')->constrained()->restrictOnDelete(); $table->string('status',32)->default('pending_payment')->index(); $table->decimal('subtotal',12,2); $table->decimal('discount_amount',12,2)->default(0); $table->decimal('service_fee',12,2)->default(0); $table->decimal('total_amount', 12, 2); $table->char('currency',3)->default('BDT'); $table->timestampTz('expires_at')->nullable(); $table->timestampTz('confirmed_at')->nullable(); $table->timestampTz('cancelled_at')->nullable(); $table->timestampsTz(); $table->index(['user_id','created_at']); $table->index(['trip_id','status']); });
        Schema::create('trip_seats', function (Blueprint $table): void { $table->ulid('id')->primary(); $table->foreignUlid('trip_id')->constrained()->cascadeOnDelete(); $table->foreignUlid('seat_layout_seat_id')->constrained('seat_layout_seats')->restrictOnDelete(); $table->foreignUlid('booking_id')->nullable()->constrained()->nullOnDelete(); $table->string('seat_number',12); $table->decimal('fare',12,2); $table->string('status',24)->default('available')->index(); $table->timestampTz('hold_expires_at')->nullable()->index(); $table->unsignedInteger('version')->default(1); $table->timestampsTz(); $table->unique(['trip_id', 'seat_layout_seat_id']); $table->index(['trip_id','status']); });
        Schema::create('seat_holds', function (Blueprint $table): void { $table->ulid('id')->primary(); $table->string('token',64)->unique(); $table->foreignUlid('user_id')->constrained()->cascadeOnDelete(); $table->foreignUlid('trip_id')->constrained()->cascadeOnDelete(); $table->string('status',24)->default('active')->index(); $table->timestampTz('expires_at')->index(); $table->timestampsTz(); });
        Schema::create('seat_hold_items', function (Blueprint $table): void { $table->ulid('id')->primary(); $table->foreignUlid('seat_hold_id')->constrained()->cascadeOnDelete(); $table->foreignUlid('trip_seat_id')->constrained()->cascadeOnDelete(); $table->unique(['seat_hold_id','trip_seat_id']); $table->unique('trip_seat_id'); });
        Schema::create('booking_passengers', function (Blueprint $table): void { $table->ulid('id')->primary(); $table->foreignUlid('booking_id')->constrained()->cascadeOnDelete(); $table->string('full_name',120); $table->string('phone',32); $table->string('email',190)->nullable(); $table->string('document_type',24)->nullable(); $table->string('document_number',64)->nullable(); $table->string('gender',24)->nullable(); $table->date('date_of_birth')->nullable(); $table->timestampsTz(); });
        Schema::create('booking_seats', function (Blueprint $table): void { $table->ulid('id')->primary(); $table->foreignUlid('booking_id')->constrained()->cascadeOnDelete(); $table->foreignUlid('passenger_id')->constrained('booking_passengers')->cascadeOnDelete(); $table->foreignUlid('trip_seat_id')->constrained()->restrictOnDelete(); $table->decimal('fare',12,2); $table->unique(['booking_id','trip_seat_id']); $table->unique('passenger_id'); });
    }
    public function down(): void { foreach (['booking_seats','booking_passengers','seat_hold_items','seat_holds','trip_seats','bookings'] as $table) Schema::dropIfExists($table); }
};
