<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
    public function up(): void {
        Schema::create('locations', function (Blueprint $table): void { $table->ulid('id')->primary(); $table->string('name', 120); $table->string('slug', 140)->unique(); $table->string('district',120)->nullable(); $table->boolean('is_active')->default(true)->index(); $table->timestampsTz(); });
        Schema::create('operators', function (Blueprint $table): void { $table->ulid('id')->primary(); $table->string('name',120); $table->string('slug',140)->unique(); $table->string('phone',32)->nullable(); $table->string('email',190)->nullable(); $table->string('status',24)->default('active')->index(); $table->timestampsTz(); });
        Schema::create('seat_layouts', function (Blueprint $table): void { $table->ulid('id')->primary(); $table->string('name',120); $table->unsignedSmallInteger('seat_count'); $table->unsignedTinyInteger('columns')->default(4); $table->string('status',24)->default('active'); $table->timestampsTz(); });
        Schema::create('seat_layout_seats', function (Blueprint $table): void { $table->ulid('id')->primary(); $table->foreignUlid('seat_layout_id')->constrained()->cascadeOnDelete(); $table->string('seat_number',12); $table->unsignedSmallInteger('row_number'); $table->unsignedTinyInteger('column_number'); $table->unsignedTinyInteger('deck')->default(1); $table->string('seat_type',24)->default('standard'); $table->boolean('is_window')->default(false); $table->boolean('is_aisle')->default(false); $table->boolean('is_active')->default(true); $table->unique(['seat_layout_id','seat_number']); });
        Schema::create('buses', function (Blueprint $table): void { $table->ulid('id')->primary(); $table->foreignUlid('operator_id')->constrained()->restrictOnDelete(); $table->foreignUlid('seat_layout_id')->constrained()->restrictOnDelete(); $table->string('registration_number',64)->unique(); $table->string('label',120); $table->string('model',120)->nullable(); $table->string('bus_type',32)->default('ac'); $table->string('status',24)->default('active')->index(); $table->timestampsTz(); });
        Schema::create('routes', function (Blueprint $table): void { $table->ulid('id')->primary(); $table->foreignUlid('origin_location_id')->constrained('locations')->restrictOnDelete(); $table->foreignUlid('destination_location_id')->constrained('locations')->restrictOnDelete(); $table->string('code',32)->unique(); $table->unsignedSmallInteger('estimated_duration_minutes'); $table->decimal('distance_km',8,2)->nullable(); $table->string('status',24)->default('active')->index(); $table->timestampsTz(); $table->index(['origin_location_id','destination_location_id']); });
        Schema::create('route_stops', function (Blueprint $table): void { $table->ulid('id')->primary(); $table->foreignUlid('route_id')->constrained()->cascadeOnDelete(); $table->foreignUlid('location_id')->constrained('locations')->restrictOnDelete(); $table->unsignedSmallInteger('sequence'); $table->unsignedSmallInteger('arrival_offset_minutes')->nullable(); $table->unsignedSmallInteger('departure_offset_minutes')->nullable(); $table->boolean('boarding_allowed')->default(true); $table->boolean('dropping_allowed')->default(true); $table->unique(['route_id','sequence']); });
    }
    public function down(): void { foreach (['route_stops','routes','buses','seat_layout_seats','seat_layouts','operators','locations'] as $table) Schema::dropIfExists($table); }
};
