<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
    public function up(): void {
        Schema::create('payments', function (Blueprint $table): void { $table->ulid('id')->primary(); $table->string('public_id',32)->unique(); $table->foreignUlid('booking_id')->constrained()->restrictOnDelete(); $table->string('provider',32)->index(); $table->string('provider_transaction_id',120)->nullable()->index(); $table->string('idempotency_key',100)->unique(); $table->decimal('amount',12,2); $table->char('currency',3)->default('BDT'); $table->string('status',32)->default('pending')->index(); $table->timestampTz('initiated_at')->nullable(); $table->timestampTz('authorized_at')->nullable(); $table->timestampTz('paid_at')->nullable(); $table->timestampTz('failed_at')->nullable(); $table->jsonb('metadata')->nullable(); $table->timestampsTz(); });
        Schema::create('payment_events', function (Blueprint $table): void { $table->ulid('id')->primary(); $table->foreignUlid('payment_id')->constrained()->cascadeOnDelete(); $table->string('event_type',64)->index(); $table->string('provider_event_id',120)->nullable()->unique(); $table->jsonb('payload')->nullable(); $table->timestampTz('occurred_at'); $table->timestampsTz(); });
        Schema::create('refunds', function (Blueprint $table): void { $table->ulid('id')->primary(); $table->foreignUlid('payment_id')->constrained()->restrictOnDelete(); $table->foreignUlid('booking_id')->constrained()->restrictOnDelete(); $table->decimal('amount',12,2); $table->char('currency',3)->default('BDT'); $table->string('status',32)->default('requested')->index(); $table->string('provider_refund_id',120)->nullable(); $table->text('reason')->nullable(); $table->timestampTz('processed_at')->nullable(); $table->timestampsTz(); });
        Schema::create('tickets', function (Blueprint $table): void { $table->ulid('id')->primary(); $table->string('public_id',32)->unique(); $table->string('ticket_number',32)->unique(); $table->foreignUlid('booking_id')->constrained()->cascadeOnDelete(); $table->foreignUlid('passenger_id')->constrained('booking_passengers')->cascadeOnDelete(); $table->foreignUlid('trip_seat_id')->constrained()->restrictOnDelete(); $table->string('status',24)->default('issued')->index(); $table->string('qr_payload',255); $table->timestampTz('issued_at'); $table->timestampsTz(); $table->unique(['booking_id','passenger_id']); });
        Schema::create('audit_logs', function (Blueprint $table): void { $table->bigIncrements('id'); $table->foreignUlid('actor_id')->nullable()->constrained('users')->nullOnDelete(); $table->string('action',100)->index(); $table->string('entity_type',100); $table->string('entity_id',64)->nullable(); $table->jsonb('before_data')->nullable(); $table->jsonb('after_data')->nullable(); $table->string('ip_address',45)->nullable(); $table->text('user_agent')->nullable(); $table->string('request_id',64)->nullable()->index(); $table->timestampTz('created_at')->useCurrent(); $table->index(['entity_type','entity_id']); });
    }
    public function down(): void { foreach (['audit_logs','tickets','refunds','payment_events','payments'] as $table) Schema::dropIfExists($table); }
};
